### ISSUE TITLE
Please make angular-PubSub installable by npm

### ISSUE THREAD

**Issue by attila123** [georapbox/angular-PubSub#2]
Hi,

Maybe this issue is not really about npm support but the lack of releases for angular-PubSub. Please note that I am very new to both angular and npm, so please forgive and  correct my errors - if any - in the following text.

In our angular 1 application we use the npm package manager.
To install angular-PubSub with npm one needs to add this to package.json (under the "dependencies" section):

```
"angular-PubSub": "https://github.com/georapbox/angular-PubSub",
```

This is really problematic in the following ways:
- There are no releases of this package, so one cannot (easily) control which version of angular-PubSub will end in one's application. In a worst case a new commit may break the application. In other words one cannot use the "latest stable" version of angular-PubSub, because there are no releases for this project yet.
- This also means constant Internet access for our build server (to always fetch this package from git), which is also not really good.
  Usually I like to use concrete package versions for all the packages, e.g.
  "angular": "1.5.8",
  etc. This has the benefit that
- package versions used by the application do not change uncontrollably (which would happen with the ^ notation, e.g.     "angular": "^1.5.8",), so one can decide when to update packages by checking the outdated packages (by 'npm outdated'), and then updating the affected version numbers in package.json.
- packages can be locally cached by e.g. npm_lazy

So please, please I ask/beg you to:
- create an initial release of this project now and further releases when appropriate
- make sure it is npm installable (e.g. if I google search 'georapbox site:www.npmjs.org' I get nothing).

**Comment by georapbox** [comment]
Hi,

Per your request, I created an initial release of the project labeled `v0.0.1` and published on npm.

You can now find it under https://www.npmjs.com/package/angular-PubSub and install it running `npm install angular-PubSub`.

Hope this helps; let me know if any other issues.
Thanks

**Comment by attila123** [comment]
Hi,
Thank you very much! This helps a lot!

I only experienced a little bit of strangeness with npm.
'npm install --save-exact angular-PubSub' installs the package, but does not put the corresponding line to package.json. 'npm install --save angular-PubSub' however also puts the corresponding line to package.json (but without the usual ^, so "angular-PubSub": "0.0.1",). This may be some npm bug with packages only having one version?? I am currently using npm 3.10.5.
But once it is correctly in the package.json ("angular-PubSub": "0.0.1",), I can uninstall the package ('npm uninstall angular-PupSub') and then 'npm update' or 'npm install' installs the package fine (just wanted to test that this also works).
But this is really just a small thing to know about, and is not a stopper at all.

**Comment by georapbox** [comment]
You're welcome

I usually use the `~` sign for the packages I install as default but this is just my personal preference. If you need to install a specific version of a package, though, you could install it using `npm install --save angular-PubSub@0.0.1`.

BTW I just released a newer version of the project which introduces a minor but breaking change. See CHANGELOG.md for more info. So if you cannot afford to update, just stick with the v0.0.1.

Thanks

**Comment by attila123** [comment]
Thanks for the information. I stick with the exact same version, to avoid any unwanted changes.
Then I run 'npm outdated' occasionally to see if there is anything to update. In the mean time making sure that the tests still pass.
We are currently very busy, so will investigate updating this package later.
